django_form/learning_site/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail,
        name='text'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail,
        name='quiz'),
    url(r'(?P<course_pk>\d+)/create_feedback/$', views.quiz_create,
        name='create_quiz'),
    url(r'(?P<course_pk>\d+)/edit_quiz(?P<quiz_pk>\d+)/$', views.quiz_edit,
        name='edit_quiz'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

django_form/learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^suggest/$', views.suggestion_view, name='suggestion' ),
    url(r'^$', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

django_form/learning_site/courses/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Avg


DONT_UNDERSTAND_DESCRIPTION_CHOICES = (
    ('badly_explained','Badly Explained'),
    ('too_difficult', 'Too Difficult'),
    ('bad_material','Bad Material'),

)



class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')


    def __str__(self):
        return self.title


#have text based steps , video based steps quizzes steps s make abstract
class Step(models.Model):
    title = models.CharField(max_length=255)


    description = models.CharField(max_length=26, choices=DONT_UNDERSTAND_DESCRIPTION_CHOICES)

    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    version = models.IntegerField()


    class Meta:
        abstract = True
        ordering = ['order',]

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')

    #return a url String
    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })


class Quiz(Step):
    rating = models.IntegerField(default='10')
   # color = models.CharField(max_length=6, choices=COLOR_CHOICES,
    #                         default='green')


    class Meta:
        verbose_name_plural = "Quizzes"

        # return a url String

    def get_absolute_url(self):
        return reverse('courses:quiz', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })


class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order']

    #good for 'VIEW ON SITE'
    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    #add for use in shell handy and good practice
    def __str__(self):
        return self.prompt


    #what about difffernet types of Question types
class MultipleChoiceQuestions(Question):
    shuffle_answers = models.BooleanField(default=False)

class TrueFalseQuestion(Question):
    pass

class Answer(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.text

django_form/learning_site/courses/forms.py
from django import forms

from . import models


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'rating',
            'version',




        ]


class TrueFalseQuestionForm(forms.ModelForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = ['order', 'prompt']


class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = models.MultipleChoiceQuestions
        fields = [
            'order',
            'prompt',
            'shuffle_answers'
        ]

django_form/learning_site/learning_site/forms.py
from django import forms


class suggestionForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    suggestion = forms.CharField(widget=forms.Textarea)

django_form/learning_site/courses/views.py
from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from . import forms
from . import models

from django.views.generic import TemplateView
from django.contrib.auth.models import User


def course_list(request):
    courses = models.Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(models.Course, pk=pk)

    #get all steps that relate to coarse  use chain and sorted
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
                        key=lambda step: step.order)  #order by step
    return render(request, 'courses/course_detail.html', {
        'course': course,   #send out course
        'steps' : steps
    })


def text_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Text, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})


def quiz_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Quiz, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/quiz_detail.html', {'step': step})


@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk)
    form = forms.QuizForm()

    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Quiz added!")
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form, 'course': course})


@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    form = forms.QuizForm(instance=quiz)# where starting from
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST )
        if form.is_valid():
            # save back over with new data
            form.save()
            messages.success(request, "Updated {} ".format(form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())


    return render(request, 'courses/quiz_form.html',{'form':form, 'course': quiz.course})

django_form/learning_site/learning_site/views.py
from django.shortcuts import render

from . import forms


def hello_world(request):
    return render(request, 'home.html')

def suggestion_view(request):
    form = forms.suggestionForm() #instanciate from
    if request.method == "post":
        form = forms.SuggestionForm(request.POST)  #all form data come in and put into form
        if form.is_valid():
            print("good form")
    return render(request, 'suggestion_form.html', {'form':form})  #send instanciated form out t the templete

django_form/learning_site/courses/templates/courses/course_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block extrahead %}


{% endblock %}


{% block content %}
<html>
<head>
    <title>Bootstrap 101 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->

    <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
<script src="http://code.jquery.com/jquery.js"></script>

<script>
$(document).ready(function(){

        $("article").hide();
        $("#mychart_description").hide();
        $(".container_description").hide();
        $("h2").hide();



    $(".button1").click(function(){
        $("article").show();
        $("#step_tru1").hide();
        $("#step_tru2").hide();
        $(".button1").val('Save');
    });

    $(".button_description").click(function(){
        $(".container_description").show();
        show_description_chart();


    });
});

</script>

<div class="row columns">
    {{ block.super }}

    <h1 class="">{{ course.title }}</h1>

    <div class="callout secondary">
        {{ course.description}}
        v{{ course.version}}

    </div>

    <div class="callout secondary">
        {{ course.content}}


    </div>


    <article>
        FEEDBACK
        <hr>
        <div class="step_tru">
            {% for step in steps %}

            <dt>
                <div class="title">Title:<a href="{{ step.get_absolute_url }}">{{ step.title }}</a>
                    <div id="par">Rating:{{ step.rating }}</div>
            <dt>
        </div>

        <div class="description">Description:{{ step.description|markdown_to_html }}

            <hr>


        </div>
        <div class="version">version:{{ step.version }}


            {% endfor %}

        </div>

        <!-- innerHTML for rating -->

        <div id="step_tru1">
            {% for step in steps %}

            <div id="par1">{{ step.rating }}</div>

            {% endfor %}


        </div>

        <!-- innerHTML for description -->

        <div id="step_tru2">
            {% for step in steps %}

            <div id="par2">{{ step.description }}</div>


            {% endfor %}


        </div>

        <!-- innerHTML for version -->

        <div id="step_tru3">
            {% for step in steps %}

            <div id="par3">{{ step.version }}</div>


            {% endfor %}


        </div>


    </article>

    <button class="button1">Show Feedbacks</button>

    <hr>
    <a href="{% url 'courses:create_quiz' course_pk=course.id  %}" class="button">Add Feedback</a>

    </article>
</div>


<!-- Ratings Chart canvas -->
<div class="container" width="320" height="176">
    <h2> Ratings Chart </h2>
    <div>
        <canvas id="myChart" width="320" height="176"></canvas>
    </div>
</div>

<button class="button_description">Show More Charts</button>

<!-- Description Chart canvas -->
<div class="container_description" width="320" height="176">
    <h2> Description Chart </h2>
    <div>
        <canvas id="myChart_description" width="320" height="176"></canvas>
    </div>
</div>
<style type="text/css">
	    .container {
            width: 60%;
            margin: 15px auto;
                }

</style>

<style type="text/css">
	    .container_description {
            width: 60%;
            margin: 15px auto;
                }

</style>


<script type="text/javascript">

    var ctx = document.getElementById('myChart').getContext('2d');
    <!-- function for rating canvas -->
    function func(x,y,z){
    console.log(y);
    console.log("z"+z);

    var color;
        var color1 =  "rgba(153,255,51,0.6)";
         var color2 =  "rgba(34,25,5,6.6)";
          var color3 =  "rgba(100,155,23,3.6)";


        var myChart = new Chart(ctx, {
          type: 'line',
        scaleOverride : true,
        scaleSteps : 10,
        scaleStepWidth : 50,
        scaleStartValue : 0 ,
          data: {
            labels: [1,3,4,5],
            datasets: [{
              label: 'Ratings over Time',
              data: x,

              backgroundColor: color3

            }]
          }
        });


}



    var ctx_description = document.getElementById('myChart_description').getContext('2d');

     <!-- function for description canvas -->
    function func_description(x,y){


    console.log("func_description called");


    var color =  "rgba(153,255,51,0.6)";
    var myBarChart = new Chart(ctx_description, {
    type: 'bar',
    data: 'data',
    options: 'options',
     data:{
    labels: x,
    datasets: [
        {
            label: "Description Chart",
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1,

            data:y
            }]
          }
        });


}


            //Javacript for ratings function call

            var tRow = document.getElementById('step_tru1');
            var i;
            var all = new Array();
            var tRow_versionNum = document.getElementById('step_tru3');
            var all_version = new Array();
            for (i=0; i<15; i++){
            var x = tRow.children[i].innerHTML;
            all[i]=x;
            var z = tRow_versionNum.children[i].innerHTML;
            all_version[i]=z;


            func(all,all.length,z);


                                }




             //Javacript for description function call

            function show_description_chart(){

            var tRow_des = document.getElementById('step_tru2');
            var t;
            var all1 = new Array();
            for (t=0; t<5; t++){
            var x_des = tRow_des.children[t].innerHTML;
            all1[t]=x_des;




            var  count = {};

            all1.forEach(function(t) { count[t] = (count[t]||0)+1;  });// puts into key pair values

            console.log(count)


             var bad_materialkey = Object.keys(count)[0];
            var bad_materialvalue = count.bad_material;

             var badly_explainedkey = Object.keys(count)[1];
            var badly_explainedvalue = count.badly_explained;


            var too_difficultkey = Object.keys(count)[2];
            var too_difficultvalue = count.too_difficult;


            var valueArray =[bad_materialvalue,badly_explainedvalue,too_difficultvalue];
            var keyArray = [bad_materialkey,badly_explainedkey,too_difficultkey]
            console.log("valueArray"+valueArray);
              console.log("keyArray"+keyArray);





            func_description(keyArray,valueArray)

                                }


             }




</script>


{% endblock %}


</html>

django_form/learning_site/courses/templates/courses/course_list.html
{% extends "courses/layout.html" %}

{% block title %}All{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row">
        {%  for course in courses %}
            <div class="small-6 columns">
                <div class="callout">
                    <h5><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></h5>
                    <div class="card-copy">
                        {{ course.description }}
                    </div>
                </div>
            </div>

            {% if forloop.counter|divisibleby:"2" %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

django_form/learning_site/courses/templates/courses/course_nav.html
{% for course in courses %} 
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endfor %}

django_form/learning_site/courses/templates/courses/layout.html
{% extends "layout.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'courses:list' %}">Courses</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

django_form/learning_site/courses/templates/courses/quiz_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
          Quiz question Here !
        </article>
      <!--  {% if user.is_authenticated %}-->
        <hr>
        <a href="{% url 'courses:edit_quiz' course_pk=step.course.pk quiz_pk=step.pk %}"
           class = "button" >Edit</a>
      <!--  {% endif %} -->

    </div>
{% endblock %}

django_form/learning_site/courses/templates/courses/quiz_form.html
{% extends "courses/layout.html" %}

{% block title %}{{ form.instance.title|default:"New Quiz" }} | {{ course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
<div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.title|default:"Give your Feedback and rating on this course" }}</h1>
    <h9>current version is:{{ course.version }}</h9>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
</div>
{% endblock %}

django_form/learning_site/courses/templates/courses/step_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
             {% if user.is_authenticated %}

        <hr>

        {% endif %}
    </div>
{% endblock %}

django_form/learning_site/courses/templates/courses/text_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>asdasasdasdadasdasa
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}

django_form/learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
    <div class="row">
        <h1>Welcome!</h1>
    </div>
{% endblock %}

django_form/learning_site/templates/layout.html
<!doctype html>
{% load static from staticfiles %}
{% load course_extras %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block css %}{% endblock %}
        <script src="{% static 'js/vendor/modernizr.js' %}"></script>
        <meta class="foundation-mq">
    </head>
    <body>
        <nav class="top-bar" role="navigation">
            <section class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu role="menubar">
                    <li class="menu-text">The Learning Site</li>
                    <li class="has-submenu">
                        <a href="#">Courses</a>
                        <ul class="submenu menu vertical" data-submenu role="menu">
                            {% nav_courses_list %}
                            <li><a href="{% url 'courses:list' %}">See all &rarr;</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
        </nav>
        {% block content %}{% endblock %}
        <footer class="row columns">
            <hr/>
            <div class="small-6 columns">
                <p>&copy; The Learning Site</p>
            </div>
            <div class="small-6 columns">
                <ul class="inline-list no-bullet float-right">
                    <li><a href="{% url 'courses:list' %}">Courses</a></li>
                </ul>
            </div>
        </footer>
        <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/what-input.min.js' %}"></script>
        <script src="{% static 'js/foundation.min.js' %}"></script>
        {% block javascript %}{% endblock %}
        <script>$(document).foundation();</script>
    </body>
</html>

django_form/learning_site/templates/suggestion_form.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
    <div class="row">
        <h1>Suggest an idea</h1>
        <form action=" " method = "POST">
           {{ form.as_p }}  <!--form that comes in from view-->
            {% csrf_token %}
            <input type=" = submit" class = "button">

        </form>

    </div>
{% endblock %}